// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!^QYQPOOOeQQO'#CcOOQO'#Cj'#CjOOQO'#Cf'#CfQYQPOOOOQO'#Cd'#CdOOQO,58},58}OmQPO,58}OOQO-E6d-E6dOOQO1G.i1G.i",
  stateData: "r~O]OSPOS~ORQOSQOUPO~OTUOXTO~OTXO~O",
  goto: "q_PPPPPPP`dPgPPPmTQOSRVPQSORWSTROS",
  nodeNames: "⚠ LineComment Program Identifier String MustacheEnd MustacheStart Mustache MustacheContent MustacheIdentifier",
  maxTerm: 14,
  nodeProps: [
    ["openedBy", 5,"MustacheStart"],
    ["closedBy", 6,"MustacheEnd"],
    ["isolate", 7,""]
  ],
  skippedNodes: [0,1],
  repeatNodeCount: 1,
  tokenData: "%c~R^XY}YZ}]^}pq}rs!`st#|}!O$e!Q![$e!]!^#|!c!}$e#R#S$e#T#o$e#o#p${#q#r%W~!SS]~XY}YZ}]^}pq}~!cVOr!`rs!xs#O!`#O#P!}#P;'S!`;'S;=`#v<%lO!`~!}OS~~#QRO;'S!`;'S;=`#Z;=`O!`~#^WOr!`rs!xs#O!`#O#P!}#P;'S!`;'S;=`#v;=`<%l!`<%lO!`~#yP;=`<%l!`~$RSP~OY#|Z;'S#|;'S;=`$_<%lO#|~$bP;=`<%l#|R$lTRPXQ}!O$e!Q![$e!c!}$e#R#S$e#T#o$e~%OP#o#p%R~%WOU~~%ZP#q#r%^~%cOT~",
  tokenizers: [0, 1],
  topRules: {"Program":[0,2]},
  tokenPrec: 0
})
