// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  LineComment = 1,
  Program = 2,
  Identifier = 3,
  String = 4,
  MustacheEnd = 5,
  MustacheStart = 6,
  Mustache = 7,
  MustacheContent = 8,
  MustacheIdentifier = 9
